### PR TITLE
SFTP: add loadbalancerIp attribute

### PR DESCRIPTION
**Pull request by mohammed6688**
Add loadBalancerIP Attribute in service template

### CODE REVIEW

**Comment by sj14** [comment]
Thanks a lot for your contribution. I see `loadBalancerIP` is already marked as deprecated ([docs](https://kubernetes.io/docs/concepts/services-networking/service/)). Other alternatives would not work for you?

**Comment by mohammed6688** [comment]
I am using a self-hosted RKE2 cluster and KubeVip for load balancing IP allocation. I think this is the easiest way to specify a specific load balancer IP to be exposed by KubeVip.

**Comment by sj14** [comment]
I see. I've fixed the CI issues but I seem to be unable to push to your branch despite the `Maintainers are allowed to edit this pull request. ` setting, maybe because it's the main branch on your fork. Please cherry-pick this commit: https://github.com/sj14/helm-charts/commit/8bc6ce951dd0a43f5817d268e93832c52aa84640.

**Comment by mohammed6688** [comment]
done

**Comment by sj14** [comment]
Thanks again for the contribution. I've released the new chart version.

**Pull request merged**
