### PR TITLE
Add new service.nodePort in README.md

### PR DESCRIPTION
**Pull request by mossroy**
Following #6

### CODE REVIEW

**Comment by mossroy** [comment]
I'm not 100% sure my value in "default" column is right, as I'm showing an empty string for a type int...

**Comment by sj14** [comment]
Thanks for the PR. The readme is generated from the values.yaml file but as the nodePort is commented out, it's not shown in the readme. Maybe it can be activated by default but I wasn't sure if it might interfere with non NodePort types. Would need to test it first.

**Comment by mossroy** [comment]
Maybe you could uncomment it in the bundled values.yaml, but without any value? So that your "if" statements would work the same in your templates?

**Comment by sj14** [comment]
I've adjusted it in https://github.com/sj14/helm-charts/pull/8. I think this PR is not needed anymore and I will close it.

**Pull request closed without merging**
